# SPDX-License-Identifier: GPL-2.0+
#
# (C) Copyright 2000, 2001, 2002
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# (C) Copyright 2008
# Guennadi Liakhovetki, DENX Software Engineering, <lg@denx.de>

#obj-y	:= goni.o onenand.o
obj-y	:= goni.o
extra-y	+= lowlevel_init.o
extra-y	+= s5pv210_ddr_init.o
extra-y	+= s5pv210_cpcode.o
extra-y	+= s5pv210_cpcode_fun.o

